# Generated by Django 4.0 on 2021-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wind_speed', models.FloatField()),
                ('wind_speed_unit', models.CharField(choices=[('MPS', 'metre/sec'), ('MPH', 'miles/hour')], max_length=3)),
                ('wind_degree', models.IntegerField()),
                ('temperature_unit', models.CharField(choices=[('K', 'Kelvin'), ('C', 'Celsius'), ('F', 'Fahrenheit')], max_length=1)),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('main', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('BLR', 'Bengaluru'), ('MMB', 'Mumbai'), ('NY', 'New York'), ('DB', 'Dubai'), ('LND', 'London'), ('MXCT', 'Mexico City')], max_length=5)),
                ('visibility', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('avg_temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('wind_speed', models.FloatField()),
                ('wind_speed_unit', models.CharField(choices=[('MPS', 'metre/sec'), ('MPH', 'miles/hour')], max_length=3)),
                ('wind_degree', models.IntegerField()),
                ('temperature_unit', models.CharField(choices=[('K', 'Kelvin'), ('C', 'Celsius'), ('F', 'Fahrenheit')], max_length=1)),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('main', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('BLR', 'Bengaluru'), ('MMB', 'Mumbai'), ('NY', 'New York'), ('DB', 'Dubai'), ('LND', 'London'), ('MXCT', 'Mexico City')], max_length=5)),
                ('forecast_date', models.DateTimeField()),
                ('pressure', models.FloatField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
