# Generated by Django 4.0 on 2021-07-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweatherdata',
            name='city',
            field=models.CharField(choices=[('BLR', 'Bengaluru'), ('MMB', 'Mumbai'), ('NY', 'New York'), ('DB', 'Dubai'), ('LND', 'London'), ('MXCT', 'Mexico City')], max_length=5, unique=True),
        ),
        migrations.AddConstraint(
            model_name='dailyweatherdata',
            constraint=models.UniqueConstraint(fields=('forecast_date', 'city'), name='uq_dailyweather_city_date'),
        ),
    ]
