# Generated by Django 4.0 on 2021-07-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hava', '0003_alter_currentweatherdata_avg_temperature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyweatherdata',
            options={'ordering': ['forecast_date']},
        ),
    ]
